# content/seo/config.yml
# ====================================
# META DEFAULTS
# ====================================
meta:
  siteName: "Incubrain"
  titleTemplate: "%s | Incubrain - AI Automation Specialists"
  separator: "•"
  
  ogSiteName: "Incubrain"
  twitterSite: "@incubrain"
  twitterCreator: "@drewmacgibbon"
  
  defaultOgImage: "/images/og-default.jpg"
  logoImage: "/logo.png"
  
  contactInfo:
    email: "hello@incubrain.org"
    phone: "+64123456789"
    whatsapp: "+64123456789"

# ====================================
# DEFAULTS
# ====================================
defaults:
  schemas:
    - organization
    - webpage:
        name: "page.title || organization.name"
        description: "page.description || organization.description"
  ogImage:
    component: "PageOgImage"
    variant: "default"
  meta:
    titleSuffix: ""

# ====================================
# PAGE CONFIGURATIONS
# ====================================
pages:
  "/":
    schemas:
      - organization
      - person
      - service
      - website:
          name: "organization.name"
          url: "organization.url"
          potentialAction:
            "@type": "SearchAction"
            target: "{organization.url}/search?q={search_term_string}"
            query-input: "required name=search_term_string"
    ogImage:
      component: "LandingOgImage"
    meta:
      titleSuffix: "AI Automation Specialists"
      
  "/landing":
    schemas:
      - organization
      - person
      - service
      - website:
          name: "organization.name"
          url: "organization.url"
          potentialAction:
            "@type": "SearchAction"
            target: "{organization.url}/search?q={search_term_string}"
            query-input: "required name=search_term_string"
    ogImage:
      component: "LandingOgImage"
    meta:
      titleSuffix: "AI Automation Specialists"
      
  "/about":
    schemas:
      - organization
      - person
      - aboutPage:
          about: "person"
    ogImage:
      component: "AboutOgImage"
    meta:
      titleSuffix: "About Us"
      
  "/contact":
    schemas:
      - organization
      - contactPage:
          mainEntity: "organization.contactPoint"
    ogImage:
      component: "ContactOgImage"
    meta:
      titleSuffix: "Get In Touch"
      
  "/community":
    schemas:
      - organization
      - webpage:
          name: "page.title || organization.name"
          description: "page.description || organization.description"
    ogImage:
      component: "CommunityOgImage"
    meta:
      titleSuffix: "Join Our Community"

# ====================================
# CONTENT TYPE CONFIGURATIONS
# ====================================
contentTypes:
  blog:
    schemas:
      - organization
      - person
      - blogPost:
          headline: "page.title"
          description: "page.description"
          datePublished: "page.date"
          dateModified: "page.date"
          articleSection: "getCategoryName(page.category)"
          keywords: "page.tags?.join(', ')"
          wordCount: "estimateWordCount(page)"
          image: "page.image ? `{organization.url}/images/blog/{page.category}/{page.image}` : undefined"
          url: "{organization.url}{page.path}"
          author: "person"
          publisher: "organization"
          mainEntityOfPage:
            "@type": "WebPage"
            "@id": "{organization.url}{page.path}"
    ogImage:
      component: "BlogOgImage"
      categoryMapping:
        ai-automation: "TechOgImage"
        business-automation: "BusinessOgImage"
        space-tech: "SpaceOgImage"
        future-ai: "FutureOgImage"
        company-culture: "CultureOgImage"
        default: "BlogOgImage"
    meta:
      titleSuffix: "Incubrain Blog"