# Intent-driven analytics configuration
name: analytics
data:
  funnels:
    primary:
      - awareness: "landing_hero_view"
      - interest: "template_section_view" 
      - action: "github_click"
      
    secondary:
      - awareness: "services_section_view"
      - interest: "cta_hover"
      - action: "whatsapp_click"

  events:
    conversion:
      - template_download
      - consultation_request
      - social_follow
    
    engagement:
      - blog_read
      - component_demo_view
      - faq_expand

  goals:
    primary: "template_download"
    secondary: "consultation_booking"
    engagement: "blog_read_time"