schema:
  schemaType: service
  data:
    - "@type": "Service"
      name: "AI Business Process Automation"
      description: "Custom AI automation solutions for business processes with measurable ROI"
      provider:
        "@type": "Organization"
        name: "Incubrain Ltd"
      serviceType: "AI Automation"
      areaServed: "Worldwide"
      
      offers:
        "@type": "Offer"
        name: "AI Automation Consultation"
        description: "Free consultation to discover automation opportunities"
        price: "0"
        priceCurrency: "USD"
        availability: "https://schema.org/InStock"
        validFrom: "2025-01-01"
        businessFunction: "http://purl.org/goodrelations/v1#Sell"
        
    - "@type": "Service" 
      name: "Space Technology Platform Development"
      description: "Specialized platform development for space technology companies including satellite data platforms and astronomy research tools"
      provider:
        "@type": "Organization"
        name: "Incubrain Ltd"
      serviceType: "Space Technology Development"